classdef cob_segmentation_srvResponse < robotics.ros.Message
    %cob_segmentation_srvResponse MATLAB implementation of cob_wrapper/cob_segmentation_srvResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'cob_wrapper/cob_segmentation_srvResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '7588356d29ae4d5a7be1b767ee8e6d80' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        SensorMsgsImageClass = robotics.ros.msg.internal.MessageFactory.getClassForType('sensor_msgs/Image') % Dispatch to MATLAB class for message type sensor_msgs/Image
    end
    
    properties (Dependent)
        ImagesSeg
    end
    
    properties (Access = protected)
        Cache = struct('ImagesSeg', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ImagesSeg'} % List of non-constant message properties
        ROSPropertyList = {'images_seg'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = cob_segmentation_srvResponse(msg)
            %cob_segmentation_srvResponse Construct the message object cob_segmentation_srvResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function imagesseg = get.ImagesSeg(obj)
            %get.ImagesSeg Get the value for property ImagesSeg
            if isempty(obj.Cache.ImagesSeg)
                javaArray = obj.JavaMessage.getImagesSeg;
                array = obj.readJavaArray(javaArray, obj.SensorMsgsImageClass);
                obj.Cache.ImagesSeg = feval(obj.SensorMsgsImageClass, array);
            end
            imagesseg = obj.Cache.ImagesSeg;
        end
        
        function set.ImagesSeg(obj, imagesseg)
            %set.ImagesSeg Set the value for property ImagesSeg
            if ~isvector(imagesseg) && isempty(imagesseg)
                % Allow empty [] input
                imagesseg = feval([obj.SensorMsgsImageClass '.empty'], 0, 1);
            end
            
            validateattributes(imagesseg, {obj.SensorMsgsImageClass}, {'vector'}, 'cob_segmentation_srvResponse', 'ImagesSeg');
            
            javaArray = obj.JavaMessage.getImagesSeg;
            array = obj.writeJavaArray(imagesseg, javaArray, obj.SensorMsgsImageClass);
            obj.JavaMessage.setImagesSeg(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.ImagesSeg)
                obj.Cache.ImagesSeg = [];
                obj.Cache.ImagesSeg = obj.ImagesSeg;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.ImagesSeg = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.ImagesSeg = copy(obj.ImagesSeg);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            ImagesSegCell = arrayfun(@(x) feval([obj.SensorMsgsImageClass '.loadobj'], x), strObj.ImagesSeg, 'UniformOutput', false);
            obj.ImagesSeg = vertcat(ImagesSegCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ImagesSeg = arrayfun(@(x) saveobj(x), obj.ImagesSeg);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.cob_wrapper.cob_segmentation_srvResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.cob_wrapper.cob_segmentation_srvResponse;
            obj.reload(strObj);
        end
    end
end
